import { isName, validPassword } from './utils/regex';
import {
  Data,
  Endpoint,
  IterableUser,
  ObjectKey,
  ObjectType,
  RequestMethod,
  User,
} from './utils/types';
import {
  emailAlreadyInUseMessage,
  forgotPasswordMessage,
  invalidEmailMessage,
  invalidFirstNameMessage,
  invalidIsRobotMessage,
  invalidLastNameMessage,
  invalidPasswordConfirmationMessage,
  invalidPasswordMessage,
  invalidPasswordPolicyMessage,
  invalidSecurityAnswerMessage,
  passwordConfirmationIsRequiredMessage,
  passwordIsRequiredMessage,
  securityAnswerRequiredMessage,
  serverErrorMessage,
  wrongCredentialsMessage,
} from './utils/validation/validationMessages';
import fetch from './utils/fetch';
import { apiUrl, securityQuestions } from './utils/constants';
import {
  forgotPasswordSchema,
  personalInformationSchema,
  securityInformationSchema,
  signInSchema,
  signUpSchema,
} from './utils/validation/validationSchemas';
import {
  emailMax,
  emailMin,
  firstNameMax,
  firstNameMin,
  lastNameMax,
  lastNameMin,
  passwordLowercaseCharacters,
  passwordMax,
  passwordMin,
  passwordNumbers,
  passwordSpecialCharacters,
  passwordUppercaseCharacters,
  securityAnswerMax,
  securityAnswerMin,
} from './utils/validation/validationConstants';

export {
  apiUrl,
  securityQuestions,
  isName,
  validPassword,
  firstNameMin,
  firstNameMax,
  lastNameMin,
  lastNameMax,
  emailMin,
  emailMax,
  securityAnswerMin,
  securityAnswerMax,
  passwordMin,
  passwordMax,
  passwordUppercaseCharacters,
  passwordLowercaseCharacters,
  passwordNumbers,
  passwordSpecialCharacters,
  invalidFirstNameMessage,
  invalidLastNameMessage,
  invalidEmailMessage,
  invalidPasswordPolicyMessage,
  passwordIsRequiredMessage,
  passwordConfirmationIsRequiredMessage,
  invalidPasswordConfirmationMessage,
  invalidPasswordMessage,
  invalidIsRobotMessage,
  wrongCredentialsMessage,
  emailAlreadyInUseMessage,
  serverErrorMessage,
  invalidSecurityAnswerMessage,
  securityAnswerRequiredMessage,
  forgotPasswordMessage,
  personalInformationSchema,
  securityInformationSchema,
  signUpSchema,
  signInSchema,
  forgotPasswordSchema,
  fetch,
};

export type {
  ObjectKey,
  ObjectType,
  Data,
  Endpoint,
  RequestMethod,
  User,
  IterableUser,
};
